
from .noisy_sine import noisy_sine
from .two_dimensional_test_case import two_dimensional_test_case, gaussian_test, gaussian_deriv_test
from .tv_ulog1d_test_case import tv_ulog1d_test_case
from .tv_ulog2d_test_case import tv_ulog2d_test_case